package blog.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseArticle<M extends BaseArticle<M>> extends Model<M> implements IBean {

	public void setId(java.lang.Integer id) {
		set("id", id);
	}

	public java.lang.Integer getId() {
		return get("id");
	}

	public void setHtml(java.lang.String html) {
		set("html", html);
	}

	public java.lang.String getHtml() {
		return get("html");
	}

	public void setSecondcategoryid(java.lang.Integer secondcategoryid) {
		set("secondcategoryid", secondcategoryid);
	}

	public java.lang.Integer getSecondcategoryid() {
		return get("secondcategoryid");
	}

	public void setName(java.lang.String name) {
		set("name", name);
	}

	public java.lang.String getName() {
		return get("name");
	}

	public void setTime(java.util.Date time) {
		set("time", time);
	}

	public java.util.Date getTime() {
		return get("time");
	}

	public void setBrowse(java.lang.Integer browse) {
		set("browse", browse);
	}

	public java.lang.Integer getBrowse() {
		return get("browse");
	}

}
