package blog.model;

import com.jfinal.plugin.activerecord.ActiveRecordPlugin;

/**
 * Generated by JFinal, do not modify this file.
 * <pre>
 * Example:
 * public void configPlugin(Plugins me) {
 *     ActiveRecordPlugin arp = new ActiveRecordPlugin(...);
 *     _MappingKit.mapping(arp);
 *     me.add(arp);
 * }
 * </pre>
 */
public class _MappingKit {

	public static void mapping(ActiveRecordPlugin arp) {
		arp.addMapping("article", "id", Article.class);
		arp.addMapping("category_img", "id", CategoryImg.class);
		arp.addMapping("first_category", "id", FirstCategory.class);
		arp.addMapping("second_category", "id", SecondCategory.class);
		arp.addMapping("show_pictures", "id", ShowPictures.class);
		arp.addMapping("user", "id", User.class);
	}
}

