package blog.model;

import blog.model.base.BaseArticle;
import blog.utils.HtmlParse;
import com.jfinal.plugin.activerecord.Page;
import org.jsoup.nodes.Element;
import org.jsoup.select.Elements;

import java.util.List;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Article extends BaseArticle<Article> {
	public static final Article dao = new Article();

	private String contextimage;//正文图片
	private String text;//正文纯文本
	private String secondcategoryimage;//二级分类图标

	public String getContextimage() {
		return contextimage;
	}

	public void setContextimage(String contextimage) {
		this.contextimage = contextimage;
	}

	public String getText() {
		return text;
	}

	public void setText(String text) {
		this.text = text;
	}

	public String getSecondcategoryimage() {
		return secondcategoryimage;
	}

	public void setSecondcategoryimage(String secondcategoryimage) {
		this.secondcategoryimage = secondcategoryimage;
	}

	//获取最近三篇文章
	//用于首页展示
	public List<Article> getLast3Article(){
		List<Article> articleList = dao.find("select * from article ORDER BY time desc limit 0,3 ");
		for (Article article:articleList) {
			String html = article.getHtml();
			if(html!=null){
				Elements elements = HtmlParse.getInstance().getHtmlImg(html);
				//设置正文图片
				if(elements.size()>0){
					String src = "";
					for (int j = 0; j < 1; j++) {//这里只需要取出来一张照片即可
						Element element = elements.get(j);
						src = element.attr("src");
						article.setContextimage(src);
					}
				}
				//设置正文纯文本
				String text = HtmlParse.getInstance().getHtmlText(html);
				if(text.length()>170){
					text = text.substring(0, 150);
				}
				text += "...";
				article.setText(text);
				//设置二级分类图标
				int id = article.getSecondcategoryid();
				SecondCategory secondCategory = SecondCategory.dao.findById(id);
				String imgSrc = secondCategory.getImg();
				article.setSecondcategoryimage(imgSrc);
			}
		}
		return articleList;
	}

	//获取一级分类下最近六篇文章
	public List<Article> findLast6ArticByFirstCategoryId(Integer firstCategoryId){
		//根据一级分类查询二级分类
		List<SecondCategory> secondCategoryList = SecondCategory.dao.findSecondCategoryListByFirstCategoryId(firstCategoryId);
		//根据二级分类查询文章
		String querySql = "select * from article where ";
		for (int i=0;i<secondCategoryList.size();i++){
			if (i<secondCategoryList.size()-1){
				querySql += " secondcategoryid=" +secondCategoryList.get(i).getId()+" or ";
			}else{
				querySql += " secondcategoryid=" +secondCategoryList.get(i).getId();
			}
		}
		querySql += " ORDER BY time desc limit 0,6";
		List<Article> articleList = dao.find(querySql);
		for (Article article:articleList) {
			String html = article.getHtml();
			if(html!=null){
				Elements elements = HtmlParse.getInstance().getHtmlImg(html);
				//设置正文图片
				if(elements.size()>0){
					String src = "";
					for (int j = 0; j < 1; j++) {//这里只需要取出来一张照片即可
						Element element = elements.get(j);
						src = element.attr("src");
						article.setContextimage(src);
					}
				}
				//设置正文纯文本
				String text = HtmlParse.getInstance().getHtmlText(html);
				if(text.length()>170){
					text = text.substring(0, 150);
				}
				text += "...";
				article.setText(text);
				//设置二级分类图标
				int id = article.getSecondcategoryid();
				SecondCategory secondCategory = SecondCategory.dao.findById(id);
				String imgSrc = secondCategory.getImg();
				article.setSecondcategoryimage(imgSrc);
			}
		}
		return articleList;
	}


}
