package blog.model;

import blog.model.base.BaseCategoryImg;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class CategoryImg extends BaseCategoryImg<CategoryImg> {
	public static final CategoryImg dao = new CategoryImg();
}
