package blog.model;

import blog.model.base.BaseFirstCategory;

import java.util.List;

/**
 * Generated by JFinal.
 * 数据库字段名建议使用驼峰命名规则，便于与 java 代码保持一致，如字段名： userId
 */
@SuppressWarnings("serial")
public class FirstCategory extends BaseFirstCategory<FirstCategory> {
	public static final FirstCategory dao = new FirstCategory();

	/**
	 * 所有 sql 与业务逻辑写在 Model 或 Service 中，不要写在 Controller 中，养成好习惯，有利于大型项目的开发与维护
	 */

	public List<FirstCategory> firstCategorieList(){
		return dao.find("select * from first_category");
	}

}
