package blog.model;

import blog.model.base.BaseSecondCategory;

import java.util.List;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class SecondCategory extends BaseSecondCategory<SecondCategory> {
	public static final SecondCategory dao = new SecondCategory();

	public List<SecondCategory> findSecondCategoryListByFirstCategoryId(Integer firstCategoryId){
		return dao.find("select * from second_category where firstcategoryid="+firstCategoryId);
	}
}
