package blog.model;

import blog.model.base.BaseSecondCategory;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class SecondCategory extends BaseSecondCategory<SecondCategory> {
	public static final SecondCategory dao = new SecondCategory();
}
