package blog.model;

import blog.model.base.BaseShowPictures;

import java.util.List;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class ShowPictures extends BaseShowPictures<ShowPictures> {
	public static final ShowPictures dao = new ShowPictures();

	public List<ShowPictures> showPicturesList(){
		return dao.find("select * from show_pictures where choice = 1");
	}
}
